# .github/workflows/update_date.yml
name: Update Push Date

on:
  push:
    branches:
      - main

jobs:
  update-log:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current date, time, and user
        id: info
        run: echo "current_info=$(date '+%Y-%m-%d %H:%M:%S') by ${{ github.actor }}" >> $GITHUB_OUTPUT # שומר את התאריך, השעה והמשתמש במשתנה

      - name: Append info to file
        run: |
          echo "${{ steps.info.outputs.current_info }}" >> push_date.log

      - name: Commit and push updated file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add push_date.log
          git commit -m "Update push_date.log with latest push info"
          git push
